import { ArrowLeft, CheckCircle2, Download, FileText, Flag, GitBranch, Info, ScanSearch, ShieldAlert } from "lucide-react";
import { useState } from "react";
import { Link, useParams } from "wouter";
import { trpc } from "@/lib/trpc";
import type { CaseDetail as CaseDetailType } from "@shared/types";

const riskClass = (level: string) => `risk-badge ${level === "LOW" ? "risk-low" : level === "MEDIUM" ? "risk-medium" : level === "HIGH" ? "risk-high" : "risk-critical"}`;
const statusClass = (status: string) => status === "MATCH" ? "risk-badge risk-low" : status === "SUSPICIOUS" ? "risk-badge risk-medium" : "risk-badge risk-high";
const prettyDate = (date: string) => new Date(date).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" });

export default function CaseDetail() {
  const { caseId = "" } = useParams();
  const [tab, setTab] = useState("overview");
  const [decisionMessage, setDecisionMessage] = useState("");
  const utils = trpc.useUtils();
  const decisionMutation = trpc.cases.updateDecision.useMutation({
    onSuccess: async (updated) => {
      setDecisionMessage(updated?.decision ? `Decision saved: ${updated.decision}.` : "Decision saved.");
      await Promise.all([utils.cases.get.invalidate({ caseId }), utils.cases.report.invalidate({ caseId }), utils.cases.list.invalidate(), utils.dashboard.summary.invalidate()]);
    },
  });
  const detail = trpc.cases.get.useQuery({ caseId }, { enabled: Boolean(caseId), retry: false });
  const report = trpc.cases.report.useQuery({ caseId }, { enabled: Boolean(caseId), retry: false });
  const item = detail.data;
  const saveDecision = (decision: "reviewed" | "escalated") => { setDecisionMessage(""); decisionMutation.mutate({ caseId, decision }); };
  const downloadReport = () => {
    if (!report.data) return;
    const blob = new Blob([JSON.stringify(report.data, null, 2)], { type: "application/json" });
    const url = window.URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `${caseId.toLowerCase()}-screening-report.json`;
    anchor.click();
    window.URL.revokeObjectURL(url);
  };
  if (detail.isLoading) return <div className="empty-state" style={{ minHeight: 360 }}><ScanSearch size={22} color="var(--blue)" /><strong>Loading case evidence</strong><span>Preparing the synthetic evidence chain.</span></div>;
  if (!item || detail.isError) return <div><div className="page-header"><div><p className="eyebrow">Case detail</p><h1>No result available</h1><p>Submit a document to begin screening, or return to the case register.</p></div></div><div className="empty-state panel"><strong>The requested case could not be found.</strong><Link href="/history" className="button button-primary">Back to screening history</Link></div></div>;
  return <div>
    <div className="page-header"><div><Link href="/history" className="button button-quiet" style={{ marginBottom: 10, marginLeft: -7 }}><ArrowLeft size={15} /> Back to history</Link><p className="eyebrow">Screening case</p><h1>{item.caseId}</h1><p>{item.fullName} · {item.documentType} · created {prettyDate(item.createdAt)}</p></div><div className="page-actions"><button className="button button-secondary" onClick={downloadReport} disabled={!report.data}><Download size={15} /> Download report data</button></div></div>
    <div className="notice notice-warning" style={{ marginBottom: 18 }}><strong>Recommended action: {item.recommendedAction}</strong><span>Risk language describes screening signals only. A trained reviewer must make the final decision.</span></div>
    <section className="panel" style={{ marginBottom: 18 }}><div className="panel-body"><div className="score-block"><div className="score-number">{item.score}<span> / 100</span></div><div className="score-caption"><span className={riskClass(item.riskLevel)}>{item.riskLevel} RISK</span><span className="muted small">Explainable weighted screening score</span><span className="status-chip"><span className={`status-dot ${item.status === "completed" ? "status-dot-green" : "status-dot-amber"}`} /> {item.decision}</span></div></div></div></section>
    <div className="tabs" role="tablist" aria-label="Case evidence views">{[["overview", "Overview"], ["evidence", "Flagged evidence"], ["forensics", "Document forensics"], ["twin", "Digital twin"], ["timeline", "Investigation timeline"]].map(([value, label]) => <button role="tab" aria-selected={tab === value} className={`tab ${tab === value ? "tab-active" : ""}`} onClick={() => setTab(value)} key={value}>{label}</button>)}</div>
    {tab === "overview" && <div className="dashboard-grid" style={{ marginTop: 18 }}><div className="stack"><section className="panel"><div className="panel-header"><div><h2>Sub-scores</h2><p>Contributing dimensions, shown as confidence indicators.</p></div></div><div className="panel-body"><div className="subscore-list">{[["Document integrity", item.subscores.documentIntegrity], ["Identity confidence", item.subscores.identityConfidence], ["Data consistency", item.subscores.dataConsistency], ["Forensic confidence", item.subscores.forensicConfidence]].map(([label, value]) => <div className="subscore-row" key={String(label)}><span>{label}</span><div className="subscore-bar"><span style={{ width: `${value}%` }} /></div><strong>{value}</strong></div>)}</div></div></section><section className="panel"><div className="panel-header"><div><h2>Decision controls</h2><p>Record a review outcome in your operational process.</p></div><Info size={17} color="var(--blue)" /></div><div className="panel-body"><div className="page-actions" style={{ justifyContent: "flex-start" }}><button className="button button-primary" onClick={() => saveDecision("reviewed")} disabled={decisionMutation.isPending}><CheckCircle2 size={15} /> {decisionMutation.isPending ? "Saving" : "Mark reviewed"}</button><button className="button button-secondary" onClick={() => saveDecision("escalated")} disabled={decisionMutation.isPending}><Flag size={15} /> Escalate case</button></div><span className="helper" style={{ display: "block", marginTop: 11 }}>Controls record a synthetic workflow decision for this demonstration case; they do not issue official verification decisions.</span>{decisionMessage && <span className="small" role="status" style={{ color: "var(--green)", display: "block", marginTop: 8 }}>{decisionMessage}</span>}</div></section></div><aside className="stack"><section className="panel"><div className="panel-header"><div><h2>Identity record</h2><p>Structured synthetic identity fields</p></div></div><div className="panel-body"><dl className="data-definition">{[["Full name", item.identity.fullName], ["Date of birth", item.identity.dateOfBirth], ["Nationality", item.identity.nationality], ["Document number", item.identity.documentNumber], ["Document type", item.identity.documentType], ["Expiry date", item.identity.expiryDate]].map(([label, value]) => <div style={{ display: "contents" }} key={String(label)}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></div></section><div className="notice notice-info"><strong>What this means</strong><span>The score is a structured summary of document integrity, identity consistency, data consistency, and forensic signals.</span></div></aside></div>}
    {tab === "evidence" && <section className="panel" style={{ marginTop: 18 }}><div className="panel-header"><div><h2>Why was this document flagged?</h2><p>Ranked evidence items link the risk score to supporting document regions.</p></div><span className="demo-label">EXPLAINABLE RESULT</span></div><div className="evidence-list">{item.evidence.map((evidence, index) => <div className="evidence-row" key={evidence.id}><div className="evidence-index">{index + 1}</div><div><h3>{evidence.label}</h3><p>{evidence.description}</p><p style={{ marginTop: 6 }}><strong>Evidence:</strong> {evidence.valueA || evidence.valueB || "No additional value"} {evidence.valueB ? ` / ${evidence.valueB}` : ""} · <span className="muted">{evidence.location}</span></p></div><span className={statusClass(evidence.status)}>{evidence.status}</span></div>)}</div></section>}
    {tab === "forensics" && <ForensicsPanel item={item} />}
    {tab === "twin" && <DigitalTwin item={item} />}
    {tab === "timeline" && <section className="panel" style={{ marginTop: 18 }}><div className="panel-header"><div><h2>Investigation timeline</h2><p>Stage-by-stage log with event time and duration.</p></div><span className="demo-label">DEMO DATA</span></div><div className="panel-body"><div className="timeline">{item.events.map((event, index) => <div className="timeline-row" key={event.stage}><div className="timeline-time">{new Date(event.occurredAt).toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit", second: "2-digit" })}</div><div className="timeline-rail"><span className="timeline-dot" />{index < item.events.length - 1 && <span className="timeline-line" />}</div><div className="timeline-copy"><strong>{event.stage}</strong><p>{event.detail}</p></div><div className="timeline-duration">{event.durationMs} ms</div></div>)}</div></div></section>}
  </div>;
}

function ForensicsPanel({ item }: { item: CaseDetailType }) {
  const [tab, setTab] = useState("Original");
  return <section className="panel" style={{ marginTop: 18 }}><div className="panel-header"><div><h2>Document forensics</h2><p>Compare the synthetic document view with extracted evidence.</p></div><span className="demo-label">SYNTHETIC DOCUMENT</span></div><div className="tabs">{["Original", "Enhanced", "OCR", "Forensics", "Heatmap", "Metadata"].map((label) => <button className={`tab ${tab === label ? "tab-active" : ""}`} onClick={() => setTab(label)} key={label}>{label}</button>)}</div><div className="panel-body">{tab === "Metadata" ? <dl className="data-definition">{Object.entries(item.document.metadata).map(([key, value]) => <div style={{ display: "contents" }} key={key}><dt>{key}</dt><dd>{String(value)}</dd></div>)}</dl> : tab === "OCR" ? <pre style={{ margin: 0, whiteSpace: "pre-wrap", fontFamily: "inherit", fontSize: 13, lineHeight: 1.7 }}>{item.document.extractedText}</pre> : <div className="document-grid"><div className="document-preview"><SyntheticDocument /></div><div><div className="notice notice-info"><strong>{tab} view</strong><span>{tab === "Heatmap" ? "Flagged regions are outlined in the supporting evidence view." : "This view is a synthetic rendering for demonstration."}</span></div><div className="data-definition" style={{ marginTop: 16 }}><dt>File</dt><dd>{item.document.filename}</dd><dt>Issue date</dt><dd>{item.document.issueDate}</dd><dt>Expiry date</dt><dd>{item.document.expiryDate}</dd></div></div></div>}</div></section>;
}

function DigitalTwin({ item }: { item: CaseDetailType }) {
  const mismatch = item.evidence.filter((evidence: CaseDetailType["evidence"][number]) => evidence.status !== "MATCH");
  return <section className="panel" style={{ marginTop: 18 }}><div className="panel-header"><div><h2>Document digital twin</h2><p>Uploaded document beside its structured extraction, with mismatches highlighted inline.</p></div><GitBranch size={18} color="var(--blue)" /></div><div className="panel-body"><div className="document-grid"><div className="document-preview"><SyntheticDocument /></div><div><div className="notice notice-warning" style={{ marginBottom: 14 }}><strong>{mismatch.length ? `${mismatch.length} field(s) need review` : "No mismatched fields in this view"}</strong><span>Highlights are analysis evidence, not a separate verdict.</span></div><dl className="data-definition"><dt>Full name</dt><dd className={mismatch.some((e: CaseDetailType["evidence"][number]) => e.code === "name-match") ? "mismatch" : ""}>{item.identity.fullName}</dd><dt>Date of birth</dt><dd className={mismatch.some((e: CaseDetailType["evidence"][number]) => e.code === "dob-mrz") ? "mismatch" : ""}>{item.identity.dateOfBirth}</dd><dt>Document number</dt><dd className={mismatch.some((e: CaseDetailType["evidence"][number]) => e.code === "doc-number") ? "mismatch" : ""}>{item.identity.documentNumber}</dd><dt>Expiry date</dt><dd className={mismatch.some((e: CaseDetailType["evidence"][number]) => e.code === "expiry-check") ? "mismatch" : ""}>{item.identity.expiryDate}</dd><dt>Face reference</dt><dd>{item.identity.faceReference}</dd></dl></div></div></div></section>;
}

function SyntheticDocument() { return <div className="document-sheet"><div className="document-sheet-header"><strong>REPUBLIC OF DEMO DATA</strong><span className="muted small">SYNTHETIC</span></div><div className="document-sheet-grid"><div className="document-photo"><ShieldAlert size={20} /></div><div style={{ display: "grid", gap: 9 }}><div className="document-line" /><div className="document-line" style={{ width: "75%" }} /><div className="document-line" style={{ width: "58%" }} /><div className="document-line" style={{ width: "82%" }} /></div></div><div className="mrz-box">P&lt;DEMO&lt;&lt;SYNTHETIC&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;<br />P7K4221042DEMO9204188</div></div>; }
